version: "3"

services:
  app:
    build: .
    command: npm run start:dev
    ports:
      - 3333:3333
    volumes:
      - .:/app/api
      - nodemodulesapi:/app/api/node_modules

  db:
    image: 'mongo'
    container_name: MONGO_DB
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db

volumes:
  db: {}
  nodemodulesapi: {}

